const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store=(k,v)=>localStorage.setItem(k,JSON.stringify(v)); const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0);location.hash=id==='home'?'':id}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
const validHash=location.hash.slice(1); if(validHash&&document.getElementById(validHash))showView(validHash);
function tickClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});$('#today').textContent=d.toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'});$('#dayProgress').textContent=`TODAY ${Math.round((d.getHours()*60+d.getMinutes())/14.4)}%`};tickClock();setInterval(tickClock,1000);
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark'))};if(localStorage.getItem('dark')==='true')document.body.classList.add('dark');
// tasks
let tasks=load('sd-tasks',[]);function renderTasks(){const ul=$('#taskList');ul.innerHTML='';tasks.forEach((t,i)=>{const li=document.createElement('li');li.className=t.done?'done':'';li.innerHTML=`<input type="checkbox" ${t.done?'checked':''}><span></span><button aria-label="削除">×</button>`;li.querySelector('span').textContent=t.text;li.querySelector('input').onchange=e=>{tasks[i].done=e.target.checked;saveTasks()};li.querySelector('button').onclick=()=>{tasks.splice(i,1);saveTasks()};ul.append(li)});$('#taskCount').textContent=`${tasks.filter(t=>t.done).length} / ${tasks.length}`};function saveTasks(){store('sd-tasks',tasks);renderTasks()}$('#taskForm').onsubmit=e=>{e.preventDefault();const v=$('#taskInput').value.trim();if(v){tasks.push({text:v,done:false});$('#taskInput').value='';saveTasks()}};renderTasks();
// stopwatch
let swTime=0,swStartAt=0,swTimer=null,laps=[];function fmt(ms,cs=true){let total=Math.floor(ms/10),c=total%100,s=Math.floor(total/100)%60,m=Math.floor(total/6000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}${cs?`<span>.${String(c).padStart(2,'0')}</span>`:''}`}function drawSw(){$('#swDisplay').innerHTML=fmt(swTime)}$('#swStart').onclick=()=>{if(swTimer){clearInterval(swTimer);swTimer=null;swTime=Date.now()-swStartAt;$('#swStart').textContent='再開'}else{swStartAt=Date.now()-swTime;swTimer=setInterval(()=>{swTime=Date.now()-swStartAt;drawSw()},20);$('#swStart').textContent='停止'}};$('#swLap').onclick=()=>{if(swTime){laps.unshift(swTime);renderLaps()}};$('#swReset').onclick=()=>{clearInterval(swTimer);swTimer=null;swTime=0;laps=[];$('#swStart').textContent='スタート';drawSw();renderLaps()};$('#clearLaps').onclick=()=>{laps=[];renderLaps()};function renderLaps(){const el=$('#lapList');el.innerHTML=laps.length?laps.map(x=>`<li><span>${fmt(x).replace('<span>','').replace('</span>','')}</span></li>`).join(''):'<li class="empty">記録はまだありません</li>'}
// knowledge - static manifest + File System Access API
let notes=[];async function loadBundled(){try{const paths=await fetch('knowledge/manifest.json').then(r=>{if(!r.ok)throw 0;return r.json()});notes=await Promise.all(paths.map(async p=>({name:p.replace(/\.txt$/i,''),path:p,text:await fetch('knowledge/'+encodeURIComponent(p)).then(r=>r.text())})));$('#knowledgeNotice').textContent=`同梱ナレッジを ${notes.length} 件読み込みました。`;renderNotes()}catch{$('#knowledgeNotice').textContent='同梱データの読込にはローカルサーバーが必要です。READMEの手順で起動するか「フォルダを選択」を使用してください。'}}
$('#loadDemo').onclick=loadBundled;$('#selectFolder').onclick=async()=>{if(!window.showDirectoryPicker){$('#knowledgeNotice').textContent='このブラウザはフォルダ選択に未対応です。Chrome / Edgeで開いてください。';return}try{const dir=await showDirectoryPicker();notes=[];for await(const entry of dir.values()){if(entry.kind==='file'&&entry.name.toLowerCase().endsWith('.txt')){const f=await entry.getFile();notes.push({name:entry.name.replace(/\.txt$/i,''),path:entry.name,text:await f.text()})}}$('#knowledgeNotice').textContent=`「${dir.name}」から ${notes.length} 件読み込みました。`;renderNotes()}catch(e){if(e.name!=='AbortError')$('#knowledgeNotice').textContent='フォルダを読み込めませんでした。'}};
function renderNotes(){const q=$('#knowledgeSearch').value.trim().toLowerCase(),hits=notes.filter(n=>(n.name+' '+n.text).toLowerCase().includes(q));$('#knowledgeList').innerHTML=hits.length?hits.map((n,i)=>`<button class="knowledge-item" data-i="${notes.indexOf(n)}"><b></b><small>${n.text.length.toLocaleString()}文字</small></button>`).join(''):'<div class="empty">該当するナレッジがありません</div>';$$('.knowledge-item').forEach(b=>{const n=notes[+b.dataset.i];b.querySelector('b').textContent=n.name;b.onclick=()=>{$$('.knowledge-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#knowledgeBody').innerHTML='<h2></h2><div></div>';$('#knowledgeBody h2').textContent=n.name;$('#knowledgeBody div').textContent=n.text}})}$('#knowledgeSearch').oninput=renderNotes;loadBundled();
// calculator
const keys=['C','⌫','(',')','7','8','9','÷','4','5','6','×','1','2','3','−','0','.','=','+'];const keybox=$('#calcKeys');keys.forEach(k=>{const b=document.createElement('button');b.textContent=k;if('÷×−+'.includes(k))b.className='op';if(k==='0')b.classList.add('wide');if(k==='=')b.className='equals';b.onclick=()=>calcPress(k);keybox.append(b)});let expr='',history=load('sd-calc-history',[]);function calcPress(k){if(k==='C'){expr='';$('#calcDisplay').textContent='0'}else if(k==='⌫'){expr=expr.slice(0,-1)}else if(k==='='){calculate()}else expr+=k;$('#calcExpression').textContent=expr}function calculate(){try{const safe=expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-');if(!/^[0-9+\-*/().\s]+$/.test(safe))throw 0;const result=Function(`"use strict";return (${safe})`)();if(!Number.isFinite(result))throw 0;history.unshift({expr,result});history=history.slice(0,20);store('sd-calc-history',history);$('#calcDisplay').textContent=Number(result.toFixed(10));renderHistory();expr=String(result)}catch{$('#calcDisplay').textContent='Error'}}document.addEventListener('keydown',e=>{if(!$('#calculator').classList.contains('active'))return;const m={'Enter':'=','Backspace':'⌫','Escape':'C','*':'×','/':'÷','-':'−'};const k=m[e.key]||e.key;if(keys.includes(k)){e.preventDefault();calcPress(k)}});function renderHistory(){$('#calcHistory').innerHTML=history.length?history.map(h=>`<li><span>${h.expr}</span><b>${h.result}</b></li>`).join(''):'<li class="empty">履歴はありません</li>'}$('#clearHistory').onclick=()=>{history=[];store('sd-calc-history',history);renderHistory()};renderHistory();
// focus timer
let focusTotal=1500,focusLeft=1500,focusTimer=null,mode='FOCUS',sessions=load('sd-sessions',0);function renderFocus(){const m=Math.floor(focusLeft/60),s=focusLeft%60;$('#focusTime').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#focusMode').textContent=mode;$('#focusRing').style.strokeDashoffset=603.19*(1-focusLeft/focusTotal);$('#focusScore').textContent=sessions;$('#scoreBar').style.width=Math.min(100,sessions*12.5)+'%'}function stopFocus(){clearInterval(focusTimer);focusTimer=null;$('#focusStart').textContent='スタート'}function focusDone(){stopFocus();focusLeft=0;renderFocus();if(mode==='FOCUS'){sessions++;store('sd-sessions',sessions);renderFocus()}document.title='時間です | Study Desk';setTimeout(()=>document.title='Study Desk | 学習ダッシュボード',3000)}$('#focusStart').onclick=()=>{if(focusTimer){stopFocus()}else{focusTimer=setInterval(()=>{focusLeft--;if(focusLeft<=0)focusDone();renderFocus()},1000);$('#focusStart').textContent='一時停止'}};$('#focusReset').onclick=()=>{stopFocus();focusLeft=focusTotal;renderFocus()};$$('.mode-tabs button').forEach(b=>b.onclick=()=>{stopFocus();$$('.mode-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');focusTotal=focusLeft=+b.dataset.min*60;mode=b.dataset.mode;renderFocus()});renderFocus();